apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qz5ioquze-go 
  janus-idp.io/tekton: qz5ioquze-go
  backstage.io/kubernetes-id: qz5ioquze-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qz5ioquze-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  