apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qz5ioquze-go
  janus-idp.io/tekton: qz5ioquze-go
  backstage.io/kubernetes-id: qz5ioquze-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qz5ioquze-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
