apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qz5ioquze-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qz5ioquze-go 
  name: qz5ioquze-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: qz5ioquze-go 
